import React from 'react'

//<Head></Head>태그 추가
import Head from 'next/head'

function HeadMeta({title}) {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default HeadMeta